[package]
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
name = "rusty-bin"
version = "0.1.0"

[dependencies]
diesel = { version = "0.12.0", features = ["sqlite", "uuid"] }
dotenv = "0.10.0"
handlebars = "0.26.2"
libsqlite3-sys = { version = "0.7.2", features = ["bundled"] }
r2d2 = "0.7.2"
r2d2-diesel = "0.12.0"
rocket = "0.2.6"
rocket_codegen = "0.2.6"
rocket_contrib = "0.2.6"
uuid = "0.5.0"
